#!/bin/bash
### BEGIN INIT INFO
# Provides:          Jarvis
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Jarvis
# Description: Jarvis
#
### END INIT INFO

case "$1" in
  start)
    cd /var/www/jarvis/www/api/v1/;
    screen -X -S jarvis3 kill > /dev/null
    screen -X -S jarvis2 kill > /dev/null
    screen -X -S jarvis1 kill > /dev/null
    screen -DmS jarvis1 php Daemons/daemonCmdsQueue.php &
    screen -DmS jarvis2 php Daemons/daemonRulesTimely.php &
    sleep 10
    screen -DmS jarvis3 python Daemons/daemonReceiveRF433.py &
    echo "Jarvis started"
    ;;
  stop)
    screen -X -S jarvis3 kill
    screen -X -S jarvis2 kill
    screen -X -S jarvis1 kill
    echo "Jarvis shutting down"
    ;;
  *)
    echo "Usage: /etc/init.d/jarvis {start|stop}"
    exit 1
    ;;
esac

exit 0